all:
  children:
    mpls_routers:
      hosts:
        vMX1:
          ansible_host: 100.123.1.0
        vMX2:
          ansible_host: 100.123.1.1
        vMX4:
          ansible_host: 100.123.1.3
        vMX6:
          ansible_host: 100.123.1.5
  vars:
    ansible_user: jcluser
    ansible_password: Juniper!1
    ansible_network_os: junos
    ansible_connection: netconf
    ansible_network_os: junipernetworks.junos.junos
    ansible_host_key_checking: false
