all:
  children:
    mpls_routers:
      hosts:
        vMX5:
          ansible_host: 100.123.1.4
  vars:
    ansible_username: jcluser
    ansible_password: Juniper!1
    ansible_connection: netconf
    ansible_network_os: junipernetworks.junos.junos
    ansible_host_key_checking: false
