- name: Configure OSPF on all routers
  hosts: mpls_routers
  gather_facts: no
  tasks:

    - name: vMX1 OSPF config
      when: inventory_hostname == "vMX1"
      junos_config:
        lines:
          - set protocols ospf area 0 interface ge-0/0/0.0
          - set protocols ospf area 0 interface lo0.0

    - name: vMX2 OSPF config
      when: inventory_hostname == "vMX2"
      junos_config:
        lines:
          - set protocols ospf area 0 interface ge-0/0/3.0
          - set protocols ospf area 0 interface ge-0/0/0.0
          - set protocols ospf area 0 interface lo0.0

    - name: vMX4 OSPF config
      when: inventory_hostname == "vMX4"
      junos_config:
        lines:
          - set protocols ospf area 0 interface ge-0/0/0.0
          - set protocols ospf area 0 interface ge-0/0/3.0
          - set protocols ospf area 0 interface lo0.0

    - name: vMX6 OSPF config
      when: inventory_hostname == "vMX6"
      junos_config:
        lines:
          - set protocols ospf area 0 interface ge-0/0/3.0
          - set protocols ospf area 0 interface lo0.0
