- name: Enable MPLS on interfaces
  hosts: mpls_routers
  gather_facts: no
  tasks:

    - name: vMX1 MPLS config
      when: inventory_hostname == "vMX1"
      junipernetworks.junos.junos_config:
        lines:
          - set protocols mpls interface ge-0/0/3.0

    - name: vMX2 MPLS config
      when: inventory_hostname == "vMX2"
      junipernetworks.junos.junos_config:
        lines:
          - set protocols mpls interface ge-0/0/3.0
          - set protocols mpls interface ge-0/0/0.0

    - name: vMX4 MPLS config
      when: inventory_hostname == "vMX4"
      junipernetworks.junos.junos_config:
        lines:
          - set protocols mpls interface ge-0/0/0.0
          - set protocols mpls interface ge-0/0/3.0

    - name: vMX6 MPLS config
      when: inventory_hostname == "vMX6"
      junipernetworks.junos.junos_config:
        lines:
          - set protocols mpls interface ge-0/0/3.0
