- name: Configure LDP for MPLS label distribution
  hosts: mpls_routers
  gather_facts: no
  tasks:

    - name: vMX1 LDP config
      when: inventory_hostname == "vMX1"
      junos_config:
        lines:
          - set protocols ldp interface ge-0/0/0.0
          - set protocols ldp transport-address 1.1.1.1

    - name: vMX2 LDP config
      when: inventory_hostname == "vMX2"
      junos_config:
        lines:
          - set protocols ldp interface ge-0/0/0.0
          - set protocols ldp interface ge-0/0/1.0
          - set protocols ldp transport-address 2.2.2.2

    - name: vMX4 LDP config
      when: inventory_hostname == "vMX4"
      junos_config:
        lines:
          - set protocols ldp interface ge-0/0/0.0
          - set protocols ldp interface ge-0/0/1.0
          - set protocols ldp transport-address 3.3.3.3

    - name: vMX6 LDP config
      when: inventory_hostname == "vMX6"
      junos_config:
        lines:
          - set protocols ldp interface ge-0/0/0.0
          - set protocols ldp transport-address 4.4.4.4

